spring:
  application:
    name: server
  datasource:
    url: ${MSSQL_URL}
    username: ${MSSQL_USERNAME}
    password: ${MSSQL_PASSWORD}
  ssl:
    bundle:
      pem:
        crazy-collectors:
          truststore:
            certificate: file:${CRAZY_COLLECTORS_CERT}
        heroku:
          truststore:
            certificate: file:${HEROKU_CERT}

server:
  port: 9443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}

discord:
  coolcodehacker:
    # It cannot be named as token. Otherwise, the env variable will override the specific profile variable... IDK why...
    token1: ${DISCORD_COOLCODEHACKER_TOKEN}
    channel: ${DISCORD_COOLCODEHACKER_CHANNEL_ID}

app:
  coordinator-auth-token: ${COORDINATOR_AUTH_TOKEN}
  instruction-url: ${INSTRUCTION_URL}